version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.1.0
    - 8.2.0
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: next
    versions:
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: husky
    versions:
    - 5.1.3
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.2.3
